FROM ubuntu:16.04

RUN apt-get update
RUN apt-get install -y apt-utils
RUN apt-get install -y sudo
RUN apt-get install -y software-properties-common
RUN add-apt-repository ppa:deadsnakes/ppa
RUN apt-get update

RUN apt-get install -y python3.6
RUN apt-get install -y python3-pip

RUN apt-get install -y git
RUN pip3 install virtualenv
RUN virtualenv -p /usr/bin/python3.6 fiveai
RUN ./fiveai/bin/pip3.6 install cherrypy==18.0.1
RUN  git clone https://github.com/blissnd/five_ai.git fiveai/git
RUN ./fiveai/bin/pip3.6 install requests

EXPOSE 5000/tcp
WORKDIR /fiveai/git/giphy-service

COPY ./start_script.sh  /fiveai/

ENTRYPOINT ["/fiveai/start_script.sh"]

